on:
  push:
    branches:
      - traduccion
  pull_request:
    branches:
      - traduccion
  # schedule:
  #   # run every day at 11 PM
  #   - cron: '0 23 * * *'

name: Build book

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Get R version
        id: get-r-version
        run: echo "version=$(Rscript -e 'cat(as.character(getRversion()))')" >> $GITHUB_OUTPUT
        shell: bash  

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ steps.get-r-version.outputs.version }}-3-

      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps()
        shell: Rscript {0}

      - name: Cache bookdown results
        uses: actions/cache@v3
        with:
          path: _bookdown_files
          key: bookdown-3-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-3-

      - name: Build site
        run: |
          # Allows [implcit heading links] to work; will need to convert
          # to explicit before switching to visual editor
          options(bookdown.render.file_scope = FALSE)
          bookdown::render_book("index.Rmd")
        shell: Rscript {0}

      - name: Copy docs to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noemail@cienciade.datos"

          # delete gh-pages remote branch if it exists
          git push origin --delete gh-pages

          # clone gh-pages branch
          git checkout -b gh-pages
          
          # remove all files except .git and docs
          find . -maxdepth 1 ! -name .git ! -name docs ! -name . ! -name .. -exec rm -rf {} \;

          mv docs/* .

          # create an empty .nojekyll file (otherwise github pages will ignore files starting with underscore)
          touch .nojekyll

          git add .
          git commit -m "Update gh-pages"
          
          git push origin gh-pages
        shell: bash
